### ISSUE TITLE
BFB 13/14 - must check for two-letter strings in comments? (e.g. [PW], [8B], [4])

### ISSUE THREAD

**Issue by paintspotinfez** [lithiumjs/bfb-votes-collector#4]
Hello,

With the release of BFB 13 (and given the lack of a working live vote counter at the moment), I was trying to see what the vote counts were so far for this episode. These votes in this episode are done using a two-character code (or, for some, a one-character code) - like "[PW]", "[LY]", "[CK]", "[8B]", etc. but for some a one-character code like "[4]" or "[X]".

I tried to fiddle with the code for the votes collector on my own computer, but to no avail (mostly because I know very little about Js or code in general, haha). I know in index.js there's a string that someone can change on their own if they need to change up the alphabet they're using, but I'd have no idea how to get it to use two-character strings. Given that this might be how voting is done in the future (who knows), it might be beneficial to implement the ability to search for codes of a different length. Nonetheless, how would someone search for a non-monocharacter code if they wanted to?

Thanks!

-Paintspot Infez

**Comment by lithiumjs** [comment]
That's a very interesting idea, I'll look into that. Though, I don't think that's how the voting's going to be done in the next episodes, because "voting" in BFB 13 won't affect BFB 14, and is probably done to see which characters to develop in the future.

I can suggest using an object instead of array in `config.json`, but that might decrease user-friendliness.
